on:
  push:
    tags:
    - "v[0-9]*.[0-9]*.[0-9]*"
    - "v[0-9]*.[0-9]*.[0-9]*-pre*"
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '10.x'
    - name: Set VERSION variable from tag
      shell: bash
      run: |
        TAG="${GITHUB_REF_NAME#v}"
        if [[ "${TAG}" == *"-pre"* ]]; then
          VERSION="${TAG%%-pre*}-pre"
        else
          VERSION="${TAG}"
        fi
        echo "VERSION=${VERSION}" >> "$GITHUB_ENV"
    - name: Test
      run: dotnet test tools-dotnet.sln --configuration Release
    - name: Pack
      run: dotnet pack --configuration Release /p:Version=${VERSION} --output .
    - name: Push
      run: dotnet nuget push tools-dotnet.${VERSION}.nupkg -s https://api.nuget.org/v3/index.json --api-key ${NUGET_SECRET}
      env:
        NUGET_SECRET: ${{ secrets.NUGET_SECRET }}
